const JWT_USER_PASSWORD = process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD = process.env.JWT_ADMIN_PASSWORD;

const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID;
const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET;

module.exports = {
  JWT_ADMIN_PASSWORD,
  JWT_USER_PASSWORD,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
};
